version: '3'

services:
  # Studentlist api service
  api:
    container_name: api
    image: api:latest
    volumes:
      - ./simple_api/student_age.json:/data/student_age.json
    ports:
      - 5001:5000

  #Front-end PHP app that shows list of students
  website:
    image: php:apache
    container_name: app
    volumes:
      - ./website:/var/www/html
    environment:
      USERNAME=toto
      PASSWORD=python
    ports:
      - 80:80
    depends_on:
      - api


