version: '3'

services:

  # POZOS private registry that stores images
  registry:
    container_name: registry-ctn
    image: registry
    ports:
      - 5000:5000

  # Dashboard for private registry that helps manage images
  registry-front:
    image: joxit/docker-registry-ui:static
    ports:
      - 8080:80
    environment:
      - REGISTRY_TITLE=POZOS Private Docker Registry
      - REGISTRY_URL=http://registry-ctn:5000
    depends_on:
      - registry


