FROM python:2.7-stretch
LABEL maintainer="Essodina Jean-Pascal MEWENEMESSE 305028@supinfo.com"
WORKDIR /
COPY ./student_age.py .
RUN apt-get update -y && apt-get install python-dev python3-dev libsasl2-dev python-dev libldap2-dev libssl-dev -y \
    && pip install flask flask_httpauth flask_simpleldap python-dotenv
VOLUME ["/data"]
EXPOSE 5000
CMD [ "python", "./student_age.py" ]
